### ISSUE TITLE
suggest a good  repository name

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#130]
please suggest a good, non-generic name that will be good to remember. 
Also, we are planning to make a website from this, So that will be the domain name of the website too.
suggest your suggestion by commenting below. 🥇

**Comment by Kaustubh-Natuskar** [comment]
Yeah sure 😃

**Comment by sambhavsaxena** [comment]
how about Project-Placement, can't think of anything better but still better than what currently is :))

**Comment by Kaustubh-Natuskar** [comment]
> how about Project-Placement, can't think of anything better but still better than what currently is :))

Nahh, it sounds like something generalized. We also want to make website around this idea. Keep trying.

**Comment by Kaustubh-Natuskar** [comment]
i've came up with name "moreThanFAANG"

**Comment by AnkittSharmaa** [comment]
MoreThanFAANG seems pretty good.
