### ISSUE TITLE
FAANGM?? Facebook is meta now

### ISSUE THREAD

**Issue by code1511** [Kaustubh-Natuskar/moreThanFAANGM#180]
As we know Facebook is renamed as META Then how FAANGM??

**Comment by Kaustubh-Natuskar** [comment]
I forgot suggest some names then

**Comment by ayush-sleeping** [comment]
Simple:-

" MAANG "

**Comment by mia-is-here** [comment]
MMANGA

**Comment by Kaustubh-Natuskar** [comment]
> MMANGA

Pronounce it!
Does it sound good ?

**Comment by code1511** [comment]
we can name it as "topPBCs"

**Comment by Kaustubh-Natuskar** [comment]
> we can name it as "topPBCs"

yup, we can do that but now I think we should be more generalized. I think it doesn't make any sense to just only adding top companies not everyone is looking for it and neither is everyone prepared for it. it is better if we just add more companies rather than just some top PBCs or startups.
