### ISSUE TITLE
Add classplus

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#183]

**Comment by ayush-sleeping** [comment]
Hey @Kaustubh-Natuskar , Classplus online post their job related post on linkedin , 

so can we add this link -> https://www.linkedin.com/jobs/classplus-jobs/?originalSubdomain=in 

let me know ???

**Comment by Kaustubh-Natuskar** [comment]
@ayush-sleeping yes why not!

**Comment by ayush-sleeping** [comment]
hey @Kaustubh-Natuskar , Kindly close this issue ( Issue is already solved ) .
