### ISSUE TITLE
Add protegrity

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#185]

**Comment by ayush-sleeping** [comment]
Hey @Kaustubh-Natuskar , Can I fix this issue .

**Comment by Kaustubh-Natuskar** [comment]
Try to fix all issues where we have to add single companies 😃

**Comment by ayush-sleeping** [comment]
hey @Kaustubh-Natuskar , Kindly close this issue ( Issue is already solved ) .
