### ISSUE TITLE
Companies from leetcode (B section)

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#197]
Baidu
Bilizzard
Bloomberg
Box

**Comment by adij1206** [comment]
Can I resolve this issue?

**Comment by adij1206** [comment]
> Baidu Bilizzard Bloomberg Box

Here bilizzard means Blizzard

**Comment by Kaustubh-Natuskar** [comment]
> > Baidu Bilizzard Bloomberg Box
> 
> Here bilizzard means Blizzard

Change it then. But only add if it have atleast 10000 followers and employees are more than 1000

**Comment by adij1206** [comment]
this criteria is for all the comapnies?
