### ISSUE TITLE
Companies to add from leetcode section (F section)

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#200]
Fallible
Fidesa
Flexport
ForUsAll

**Comment by adij1206** [comment]
Can I add All these Company?

**Comment by Kaustubh-Natuskar** [comment]
> Can I add All these Company?

Yes you can, but first check their pages on LinkedIn. If they have less followers (less than 20000) dont add them.

**Comment by adij1206** [comment]
Only Flexport has more than 20k followers

**Comment by adij1206** [comment]
> > Can I add All these Company?
> 
> Yes you can, but first check their pages on LinkedIn. If they have less followers (less than 20000) dont add them.
I had added Flexport only according to this criteria

**Comment by adij1206** [comment]
I had added the company according to above criteria

**Comment by adij1206** [comment]
You can close the issue
