### ISSUE TITLE
Add aptiv

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#206]

**Comment by adij1206** [comment]
It has been added

**Comment by Kaustubh-Natuskar** [comment]
> It has been added. You can close it

You can Directly close it also just add  closed #issue-number it will closed automatically efter sucessfull PR.

**Comment by adij1206** [comment]
close #206

**Comment by ayush-sleeping** [comment]
"Aptiv" is already successfully merged in #208 , Therefore closing this issue .
