### ISSUE TITLE
Add  DBS

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#209]

**Comment by adij1206** [comment]
are you refering to DBS Bank?

**Comment by adij1206** [comment]
I am adding rest of the company.

**Comment by adij1206** [comment]
@ayush-sleeping  Only DBS has not been added in this.SO may be you can close this or either you can edit the title for this issue

**Comment by Kaustubh-Natuskar** [comment]
> @ayush-sleeping  Only DBS has not been added in this.SO may be you can close this or either you can edit the title for this issue

Title changed.
