### ISSUE TITLE
Twitter button 😅

### ISSUE THREAD

**Issue by Kaustubh-Natuskar** [Kaustubh-Natuskar/moreThanFAANGM#227]
I forgot to change the content of Twitter button 😸.

**Comment by Kaustubh-Natuskar** [comment]
@ayush-sleeping solve this if possible, I'm stuck on some other work.

**Comment by ayush-sleeping** [comment]
@Kaustubh-Natuskar , I am little bit confused, Can you describe more ( What do you mean here )..........
So that I can solve this issue .

**Comment by Kaustubh-Natuskar** [comment]
> @Kaustubh-Natuskar , I am little bit confused, Can you describe more ( What do you mean here )..........
> So that I can solve this issue .

Click on that Twitter badge. 
Actually i copied it from another repository and Directly pasted ot here. So it have their description rather than ours
![Screenshot_2022-01-05-19-50-23-64.jpg](https://user-images.githubusercontent.com/64963969/148232789-e59dc6c4-e1de-49bd-af0d-4b3ec8440c6a.jpg)
![Screenshot_2022-01-05-19-49-58-53.jpg](https://user-images.githubusercontent.com/64963969/148232750-99e6beab-b2f7-427b-9ef7-1156b39f5f2f.jpg)
As you can see here. It is not even web friendly. We cannot use GitHub pages with what we have right now. 
Ao change the description for Twitter badge and check if it is web friendly.
Hope it helps 🤠

**Comment by ayush-sleeping** [comment]
Hey @Kaustubh-Natuskar , Have you seen ........... Now it also web friendly [here](https://kaustubh-natuskar.github.io/moreThanFAANGM/) .
Task Completed

**Comment by ayush-sleeping** [comment]
Now you can close this issue ......

**Comment by Kaustubh-Natuskar** [comment]
thank you man, great work
