### ISSUE TITLE
Add "Tech Mahindra" career page .

### ISSUE THREAD

**Issue by ayush-sleeping** [Kaustubh-Natuskar/moreThanFAANGM#232]
Add Tech Mahindra career page, and don't forget to increase the count.

Also, after creating a PR , Make sure to mention issue no. in the PR's comment section .
In ex.  :-   (  Fixed issue - #499496  )

**Comment by Kaustubh-Natuskar** [comment]
> Add Tech Mahindra career page, and don't forget to increase the count.
> 
> Also, after creating a PR , Make sure to mention issue no. in the PR's comment section . In ex. :- ( Fixed issue - #499496 )

ping me on linkedin
