### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by VenomFate-619** [Kaustubh-Natuskar/moreThanFAANGM#259]
Links not working for the following companies 
- acko
- agilesolutions

there can be more I haven't yet checked, I think it may be impossible to review everyone manually

**Comment by Kaustubh-Natuskar** [comment]
yeah there too much links, But this is the only way i guess. will change them later. If possible you ca do that too.

**Comment by Kaustubh-Natuskar** [comment]
So I'll create a Script which will do this work. will automatically scan the whole list.

**Comment by Kaustubh-Natuskar** [comment]
@VenomFate-619 I'm working on CLI script that will dynamically download the website content and will give us a list of links which are broken.
Thank you for suggesting this :)
