### ISSUE TITLE
Steps to add a workplace 

### ISSUE THREAD

**Issue by jesusalberto18** [Kaustubh-Natuskar/moreThanFAANGM#267]
Hello 👋 Good morning from Venezuela

I know a couple of companies/startups that would be a good git for this list.

Reply if PRs are been accepted in this repo

**Comment by Kaustubh-Natuskar** [comment]
Yes, we do.

**Comment by jesusalberto18** [comment]
Thanks @Kaustubh-Natuskar , I'll close this issue and soon I'll be doing a PR.
